travis:
  secure:
    BINSTAR_TOKEN: NOS180SxlumKRqeaU6QTC8hRdX4e8L+Jg6z/jRS+E4WLKmA+CdQT+S9slVc+gUpNPyrjLLLVMhlJgs/oVr38Tk16gje6ymF4+5Q/Baj6pCLP73qpvUXizFLmdKmYliykWmbES27GqTkbwGyaUXpgf4MCT6UDftbyqIFif7hq8MhiExnVKHi/ykOtLj2fu5W4Qi4/k8HEusjDAhrTj2WkSlCM5TCVK0/sD2Ww8ahrSujhZ6QmbOUvCU8H/QXieJvoBvsPaEMKWCLr3C8Sm6XYTALAsq5zsYMjllRySkOizZMUOjJoxYGUzbnlGBy9wfbFj2BlML0IxYWs6gGzkYavMR70DumHFb6jg3h8e4ibOG5HoRhI1PO+J2dHlwMmM3eYOVQKzQFmx5GnmIsPUwgTeaWfbaf8s2/Ge++w/bg1ynXbGvAJ1UGeEjhZxlbzQPF4zxARUkmBZ4eM0W9wO+dV4p7kN6THwv7J+lBcT/7fXAti/PnA8mJuMcR7mnz1L0IzE2zrZ7Uiz5Ypg3BC15yGvp/9LyEE/Wer0szoKizUZzVx5spBfNGZQkTfB03OPb0J1/mlcFeQY6A3cgx03kV2ulUwJk8MXBqLXz3Yfnzy9CSboTHZ5g5b8QSthpF0HncjOIEPwogp2uQmV3ZP8SZ9AsOWU/a7b3kIAat26VI+V6g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
